version: '3'
services:
  app:
    build: .
    depends_on:
      - solr
    ports:
      - "8080:8080"
    environment:
      - SOLR_HOST=solr
  solr:
    image: solr
    command: solr-create -c product
    ports:
      - "8981:8983"
